FROM alpine:3.19
RUN apk add --no-cache sqlite
WORKDIR /db

COPY init_db.sh /db/init_db.sh
COPY schema.sql /db/schema.sql

RUN chmod +x /db/init_db.sh

RUN echo "checking files"
RUN ls -l /db

CMD ["/bin/sh", "-c", "/bin/sh /db/init_db.sh && tail -f /dev/null"]
