services:
  dinner_prepper:
    build: .
    image: dinner_prepper:latest
    container_name: dinner_prepper
    volumes:
      - /src/dinner_prepper
      - ./db:/db
    working_dir: /src/dinner_prepper
    command: []  # Optional: Specify default args or commands
    restart: on-failure
      
volumes:
  db:
